In [1]:
import pandas as pd
df=pd.read_excel(r"C:\Users\user\Desktop\20 Assignments\Association Rules\Online retail.xlsx")
df

     shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
0                                burgers,meatballs,eggs
1                                               chutney
2                                        turkey,avocado
3     mineral water,milk,energy bar,whole wheat rice...
4                                        low fat yogurt
...                                                 ...
7495                      butter,light mayo,fresh bread
7496  burgers,frozen vegetables,eggs,french fries,ma...
7497                                            chicken
7498                                 escalope,green tea
7499    eggs,frozen smoothie,yogurt cake,low fat yogurt

[7500 rows x 1 columns]

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7500 entries, 0 to 7499
Data columns (total 1 columns):
 #   Column                                                                                                                                                                                                                           Non-Null Count  Dtype
---  ------                                                                                                                                                                                                                           --------------  -----
 0   shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil  7500 non-null   object
dtypes: object(1)
memory usage: 58.7+ KB

In [3]:
df.columns

Index(['shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil'], dtype='object')

In [4]:
df.shape

(7500, 1)

In [5]:
df.describe()

       shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
count                                                7500
unique                                               5175
top                                               cookies
freq                                                  223

In [6]:
df.isnull()

      shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
0                                                 False
1                                                 False
2                                                 False
3                                                 False
4                                                 False
...                                                 ...
7495                                              False
7496                                              False
7497                                              False
7498                                              False
7499                                              False

[7500 rows x 1 columns]

In [7]:
df.isnull().sum()

shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil    0
dtype: int64

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7500 entries, 0 to 7499
Data columns (total 1 columns):
 #   Column                                                                                                                                                                                                                           Non-Null Count  Dtype
---  ------                                                                                                                                                                                                                           --------------  -----
 0   shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil  7500 non-null   object
dtypes: object(1)
memory usage: 58.7+ KB

In [9]:
df.fillna('Unknown', inplace=True)

In [10]:
df.drop_duplicates(inplace=True)

In [11]:
data = {
    'TransactionID': [1, 2, 3, 4],
    'Products': [
        ['shrimp', 'almonds', 'avocado'],
        ['vegetables mix', 'green grapes', 'whole wheat flour'],
        ['yams', 'cottage cheese', 'energy drink'],
        ['tomato juice', 'low fat yogurt', 'green tea', 'honey']
    ]
}

In [12]:
df = pd.DataFrame(data)
df

   TransactionID                                           Products
0              1                         [shrimp, almonds, avocado]
1              2  [vegetables mix, green grapes, whole wheat flour]
2              3               [yams, cottage cheese, energy drink]
3              4   [tomato juice, low fat yogurt, green tea, honey]

In [13]:
all_products = ['shrimp', 'almonds', 'avocado', 'vegetables mix', 'green grapes', 'whole wheat flour', 
                'yams', 'cottage cheese', 'energy drink', 'tomato juice', 'low fat yogurt', 'green tea', 
                'honey', 'salad', 'mineral water', 'salmon', 'antioxidant juice', 'frozen smoothie', 
                'spinach', 'olive oil']

In [14]:
def one_hot_encode(transaction_list, all_products):
    return [1 if product in transaction_list else 0 for product in all_products]

In [53]:
basket_encoded = df['Products'].apply(lambda x: one_hot_encode(x, all_products))

In [55]:
basket_encoded_df = pd.DataFrame(basket_encoded.tolist(), columns=all_products)

In [57]:
basket_encoded_df['TransactionID'] = df['TransactionID']

In [59]:
basket_encoded_df.set_index('TransactionID', inplace=True)
basket_encoded_df

,shrimp,almonds,avocado,vegetables mix,green grapes,whole wheat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxidant juice,frozen smoothie,spinach,olive oil
TransactionID,,,,,,,,,,,,,,,,,,,,
1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,1,1,1,1,0,0,0,0,0,0,0

In [19]:
df.columns

Index(['TransactionID', 'Products'], dtype='object')

In [20]:
!pip install mlxtend

Requirement already satisfied: mlxtend in c:\users\user\anaconda3\lib\site-packages (0.23.4)
Requirement already satisfied: scipy>=1.2.1 in c:\users\user\anaconda3\lib\site-packages (from mlxtend) (1.13.1)
Requirement already satisfied: numpy>=1.16.2 in c:\users\user\anaconda3\lib\site-packages (from mlxtend) (1.26.4)
Requirement already satisfied: pandas>=0.24.2 in c:\users\user\anaconda3\lib\site-packages (from mlxtend) (2.2.2)
Requirement already satisfied: scikit-learn>=1.3.1 in c:\users\user\anaconda3\lib\site-packages (from mlxtend) (1.5.1)
Requirement already satisfied: matplotlib>=3.0.0 in c:\users\user\anaconda3\lib\site-packages (from mlxtend) (3.9.2)
Requirement already satisfied: joblib>=0.13.2 in c:\users\user\anaconda3\lib\site-packages (from mlxtend) (1.4.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\user\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (1.2.0)
Requirement already satisfied: cycler>=0.10 in c:\users\user\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\user\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (4.51.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\user\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (1.4.4)
Requirement already satisfied: packaging>=20.0 in c:\users\user\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (24.1)
Requirement already satisfied: pillow>=8 in c:\users\user\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (10.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\user\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (3.1.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\user\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\user\anaconda3\lib\site-packages (from pandas>=0.24.2->mlxtend) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\user\anaconda3\lib\site-packages (from pandas>=0.24.2->mlxtend) (2023.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\user\anaconda3\lib\site-packages (from scikit-learn>=1.3.1->mlxtend) (3.5.0)
Requirement already satisfied: six>=1.5 in c:\users\user\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.0.0->mlxtend) (1.16.0)

In [21]:
from mlxtend.frequent_patterns import apriori, association_rules
frequent_itemsets = apriori( basket_encoded_df,min_support=0.05, use_colnames=True)

C:\Users\user\anaconda3\Lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:161: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

In [22]:
rules = association_rules(frequent_itemsets, metric="lift", min_threshold=1,num_itemsets=5)

In [23]:
filtered_rules = rules[(rules['confidence'] >= 0.7) & (rules['lift'] >= 1)]

In [24]:
print("Filtered Association Rules:")
filtered_rules

Filtered Association Rules:

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(almonds),(shrimp),0.25,0.25,0.25,1.0,4.0,1.0,0.1875,inf,1.0,1.0,1.0,1.0
1,(shrimp),(almonds),0.25,0.25,0.25,1.0,4.0,1.0,0.1875,inf,1.0,1.0,1.0,1.0
2,(avocado),(shrimp),0.25,0.25,0.25,1.0,4.0,1.0,0.1875,inf,1.0,1.0,1.0,1.0
3,(shrimp),(avocado),0.25,0.25,0.25,1.0,4.0,1.0,0.1875,inf,1.0,1.0,1.0,1.0
4,(almonds),(avocado),0.25,0.25,0.25,1.0,4.0,1.0,0.1875,inf,1.0,1.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81,"(tomato juice, honey)","(green tea, low fat yogurt)",0.25,0.25,0.25,1.0,4.0,1.0,0.1875,inf,1.0,1.0,1.0,1.0
82,(green tea),"(honey, tomato juice, low fat yogurt)",0.25,0.25,0.25,1.0,4.0,1.0,0.1875,inf,1.0,1.0,1.0,1.0
83,(low fat yogurt),"(green tea, tomato juice, honey)",0.25,0.25,0.25,1.0,4.0,1.0,0.1875,inf,1.0,1.0,1.0,1.0
84,(honey),"(green tea, tomato juice, low fat yogurt)",0.25,0.25,0.25,1.0,4.0,1.0,0.1875,inf,1.0,1.0,1.0,1.0
85,(tomato juice),"(green tea, honey, low fat yogurt)",0.25,0.25,0.25,1.0,4.0,1.0,0.1875,inf,1.0,1.0,1.0,1.0

In [25]:
for index, row in filtered_rules.iterrows():
    print(f"Rule {index+1}: {row['antecedents']} -> {row['consequents']}")
    print(f"Support: {row['support']}, Confidence: {row['confidence']}, Lift: {row['lift']}")
    print("-" * 50)

Rule 1: frozenset({'almonds'}) -> frozenset({'shrimp'})
Support: 0.25, Confidence: 1.0, Lift: 4.0
--------------------------------------------------
Rule 2: frozenset({'shrimp'}) -> frozenset({'almonds'})
Support: 0.25, Confidence: 1.0, Lift: 4.0
--------------------------------------------------
Rule 3: frozenset({'avocado'}) -> frozenset({'shrimp'})
Support: 0.25, Confidence: 1.0, Lift: 4.0
--------------------------------------------------
Rule 4: frozenset({'shrimp'}) -> frozenset({'avocado'})
Support: 0.25, Confidence: 1.0, Lift: 4.0
--------------------------------------------------
Rule 5: frozenset({'almonds'}) -> frozenset({'avocado'})
Support: 0.25, Confidence: 1.0, Lift: 4.0
--------------------------------------------------
Rule 6: frozenset({'avocado'}) -> frozenset({'almonds'})
Support: 0.25, Confidence: 1.0, Lift: 4.0
--------------------------------------------------
Rule 7: frozenset({'vegetables mix'}) -> frozenset({'green grapes'})
Support: 0.25, Confidence: 1.0, Lift: 4.0
--------------------------------------------------
Rule 8: frozenset({'green grapes'}) -> frozenset({'vegetables mix'})
Support: 0.25, Confidence: 1.0, Lift: 4.0
--------------------------------------------------
Rule 9: frozenset({'vegetables mix'}) -> frozenset({'whole wheat flour'})
Support: 0.25, Confidence: 1.0, Lift: 4.0
--------------------------------------------------
Rule 10: frozenset({'whole wheat flour'}) -> frozenset({'vegetables mix'})
Support: 0.25, Confidence: 1.0, Lift: 4.0
--------------------------------------------------
Rule 11: frozenset({'green grapes'}) -> frozenset({'whole wheat flour'})
Support: 0.25, Confidence: 1.0, Lift: 4.0
--------------------------------------------------
Rule 12: frozenset({'whole wheat flour'}) -> frozenset({'green grapes'})
Support: 0.25, Confidence: 1.0, Lift: 4.0
--------------------------------------------------
Rule 13: frozenset({'yams'}) -> frozenset({'cottage cheese'})
Support: 0.25, Confidence: 1.0, Lift: 4.0
--------------------------------------------------
Rule 14: frozenset({'cottage cheese'}) -> frozenset({'yams'})
Support: 0.25, Confidence: 1.0, Lift: 4.0
--------------------------------------------------
Rule 15: frozenset({'yams'}) -> frozenset({'energy drink'})
Support: 0.25, Confidence: 1.0, Lift: 4.0
--------------------------------------------------
Rule 16: frozenset({'energy drink'}) -> frozenset({'yams'})
Support: 0.25, Confidence: 1.0, Lift: 4.0
--------------------------------------------------
Rule 17: frozenset({'energy drink'}) -> frozenset({'cottage cheese'})
Support: 0.25, Confidence: 1.0, Lift: 4.0
--------------------------------------------------
Rule 18: frozenset({'cottage cheese'}) -> frozenset({'energy drink'})
Support: 0.25, Confidence: 1.0, Lift: 4.0
--------------------------------------------------
Rule 19: frozenset({'low fat yogurt'}) -> frozenset({'tomato juice'})
Support: 0.25, Confidence: 1.0, Lift: 4.0
--------------------------------------------------
Rule 20: frozenset({'tomato juice'}) -> frozenset({'low fat yogurt'})
Support: 0.25, Confidence: 1.0, Lift: 4.0
--------------------------------------------------
Rule 21: frozenset({'green tea'}) -> frozenset({'tomato juice'})
Support: 0.25, Confidence: 1.0, Lift: 4.0
--------------------------------------------------
Rule 22: frozenset({'tomato juice'}) -> frozenset({'green tea'})
Support: 0.25, Confidence: 1.0, Lift: 4.0
--------------------------------------------------
Rule 23: frozenset({'honey'}) -> frozenset({'tomato juice'})
Support: 0.25, Confidence: 1.0, Lift: 4.0
--------------------------------------------------
Rule 24: frozenset({'tomato juice'}) -> frozenset({'honey'})
Support: 0.25, Confidence: 1.0, Lift: 4.0
--------------------------------------------------
Rule 25: frozenset({'green tea'}) -> frozenset({'low fat yogurt'})
Support: 0.25, Confidence: 1.0, Lift: 4.0
--------------------------------------------------
Rule 26: frozenset({'low fat yogurt'}) -> frozenset({'green tea'})
Support: 0.25, Confidence: 1.0, Lift: 4.0
--------------------------------------------------
Rule 27: frozenset({'honey'}) -> frozenset({'low fat yogurt'})
Support: 0.25, Confidence: 1.0, Lift: 4.0
--------------------------------------------------
Rule 28: frozenset({'low fat yogurt'}) -> frozenset({'honey'})
Support: 0.25, Confidence: 1.0, Lift: 4.0
--------------------------------------------------
Rule 29: frozenset({'green tea'}) -> frozenset({'honey'})
Support: 0.25, Confidence: 1.0, Lift: 4.0
--------------------------------------------------
Rule 30: frozenset({'honey'}) -> frozenset({'green tea'})
Support: 0.25, Confidence: 1.0, Lift: 4.0
--------------------------------------------------
Rule 31: frozenset({'almonds', 'avocado'}) -> frozenset({'shrimp'})
Support: 0.25, Confidence: 1.0, Lift: 4.0
--------------------------------------------------
Rule 32: frozenset({'almonds', 'shrimp'}) -> frozenset({'avocado'})
Support: 0.25, Confidence: 1.0, Lift: 4.0
--------------------------------------------------
Rule 33: frozenset({'avocado', 'shrimp'}) -> frozenset({'almonds'})
Support: 0.25, Confidence: 1.0, Lift: 4.0
--------------------------------------------------
Rule 34: frozenset({'almonds'}) -> frozenset({'avocado', 'shrimp'})
Support: 0.25, Confidence: 1.0, Lift: 4.0
--------------------------------------------------
Rule 35: frozenset({'avocado'}) -> frozenset({'almonds', 'shrimp'})
Support: 0.25, Confidence: 1.0, Lift: 4.0
--------------------------------------------------
Rule 36: frozenset({'shrimp'}) -> frozenset({'almonds', 'avocado'})
Support: 0.25, Confidence: 1.0, Lift: 4.0
--------------------------------------------------
Rule 37: frozenset({'vegetables mix', 'green grapes'}) -> frozenset({'whole wheat flour'})
Support: 0.25, Confidence: 1.0, Lift: 4.0
--------------------------------------------------
Rule 38: frozenset({'vegetables mix', 'whole wheat flour'}) -> frozenset({'green grapes'})
Support: 0.25, Confidence: 1.0, Lift: 4.0
--------------------------------------------------
Rule 39: frozenset({'green grapes', 'whole wheat flour'}) -> frozenset({'vegetables mix'})
Support: 0.25, Confidence: 1.0, Lift: 4.0
--------------------------------------------------
Rule 40: frozenset({'vegetables mix'}) -> frozenset({'green grapes', 'whole wheat flour'})
Support: 0.25, Confidence: 1.0, Lift: 4.0
--------------------------------------------------
Rule 41: frozenset({'green grapes'}) -> frozenset({'vegetables mix', 'whole wheat flour'})
Support: 0.25, Confidence: 1.0, Lift: 4.0
--------------------------------------------------
Rule 42: frozenset({'whole wheat flour'}) -> frozenset({'vegetables mix', 'green grapes'})
Support: 0.25, Confidence: 1.0, Lift: 4.0
--------------------------------------------------
Rule 43: frozenset({'yams', 'energy drink'}) -> frozenset({'cottage cheese'})
Support: 0.25, Confidence: 1.0, Lift: 4.0
--------------------------------------------------
Rule 44: frozenset({'yams', 'cottage cheese'}) -> frozenset({'energy drink'})
Support: 0.25, Confidence: 1.0, Lift: 4.0
--------------------------------------------------
Rule 45: frozenset({'energy drink', 'cottage cheese'}) -> frozenset({'yams'})
Support: 0.25, Confidence: 1.0, Lift: 4.0
--------------------------------------------------
Rule 46: frozenset({'yams'}) -> frozenset({'energy drink', 'cottage cheese'})
Support: 0.25, Confidence: 1.0, Lift: 4.0
--------------------------------------------------
Rule 47: frozenset({'energy drink'}) -> frozenset({'yams', 'cottage cheese'})
Support: 0.25, Confidence: 1.0, Lift: 4.0
--------------------------------------------------
Rule 48: frozenset({'cottage cheese'}) -> frozenset({'yams', 'energy drink'})
Support: 0.25, Confidence: 1.0, Lift: 4.0
--------------------------------------------------
Rule 49: frozenset({'green tea', 'low fat yogurt'}) -> frozenset({'tomato juice'})
Support: 0.25, Confidence: 1.0, Lift: 4.0
--------------------------------------------------
Rule 50: frozenset({'green tea', 'tomato juice'}) -> frozenset({'low fat yogurt'})
Support: 0.25, Confidence: 1.0, Lift: 4.0
--------------------------------------------------
Rule 51: frozenset({'tomato juice', 'low fat yogurt'}) -> frozenset({'green tea'})
Support: 0.25, Confidence: 1.0, Lift: 4.0
--------------------------------------------------
Rule 52: frozenset({'green tea'}) -> frozenset({'tomato juice', 'low fat yogurt'})
Support: 0.25, Confidence: 1.0, Lift: 4.0
--------------------------------------------------
Rule 53: frozenset({'low fat yogurt'}) -> frozenset({'green tea', 'tomato juice'})
Support: 0.25, Confidence: 1.0, Lift: 4.0
--------------------------------------------------
Rule 54: frozenset({'tomato juice'}) -> frozenset({'green tea', 'low fat yogurt'})
Support: 0.25, Confidence: 1.0, Lift: 4.0
--------------------------------------------------
Rule 55: frozenset({'honey', 'low fat yogurt'}) -> frozenset({'tomato juice'})
Support: 0.25, Confidence: 1.0, Lift: 4.0
--------------------------------------------------
Rule 56: frozenset({'tomato juice', 'low fat yogurt'}) -> frozenset({'honey'})
Support: 0.25, Confidence: 1.0, Lift: 4.0
--------------------------------------------------
Rule 57: frozenset({'tomato juice', 'honey'}) -> frozenset({'low fat yogurt'})
Support: 0.25, Confidence: 1.0, Lift: 4.0
--------------------------------------------------
Rule 58: frozenset({'low fat yogurt'}) -> frozenset({'tomato juice', 'honey'})
Support: 0.25, Confidence: 1.0, Lift: 4.0
--------------------------------------------------
Rule 59: frozenset({'honey'}) -> frozenset({'tomato juice', 'low fat yogurt'})
Support: 0.25, Confidence: 1.0, Lift: 4.0
--------------------------------------------------
Rule 60: frozenset({'tomato juice'}) -> frozenset({'honey', 'low fat yogurt'})
Support: 0.25, Confidence: 1.0, Lift: 4.0
--------------------------------------------------
Rule 61: frozenset({'green tea', 'honey'}) -> frozenset({'tomato juice'})
Support: 0.25, Confidence: 1.0, Lift: 4.0
--------------------------------------------------
Rule 62: frozenset({'green tea', 'tomato juice'}) -> frozenset({'honey'})
Support: 0.25, Confidence: 1.0, Lift: 4.0
--------------------------------------------------
Rule 63: frozenset({'tomato juice', 'honey'}) -> frozenset({'green tea'})
Support: 0.25, Confidence: 1.0, Lift: 4.0
--------------------------------------------------
Rule 64: frozenset({'green tea'}) -> frozenset({'tomato juice', 'honey'})
Support: 0.25, Confidence: 1.0, Lift: 4.0
--------------------------------------------------
Rule 65: frozenset({'honey'}) -> frozenset({'green tea', 'tomato juice'})
Support: 0.25, Confidence: 1.0, Lift: 4.0
--------------------------------------------------
Rule 66: frozenset({'tomato juice'}) -> frozenset({'green tea', 'honey'})
Support: 0.25, Confidence: 1.0, Lift: 4.0
--------------------------------------------------
Rule 67: frozenset({'green tea', 'honey'}) -> frozenset({'low fat yogurt'})
Support: 0.25, Confidence: 1.0, Lift: 4.0
--------------------------------------------------
Rule 68: frozenset({'green tea', 'low fat yogurt'}) -> frozenset({'honey'})
Support: 0.25, Confidence: 1.0, Lift: 4.0
--------------------------------------------------
Rule 69: frozenset({'low fat yogurt', 'honey'}) -> frozenset({'green tea'})
Support: 0.25, Confidence: 1.0, Lift: 4.0
--------------------------------------------------
Rule 70: frozenset({'green tea'}) -> frozenset({'low fat yogurt', 'honey'})
Support: 0.25, Confidence: 1.0, Lift: 4.0
--------------------------------------------------
Rule 71: frozenset({'honey'}) -> frozenset({'green tea', 'low fat yogurt'})
Support: 0.25, Confidence: 1.0, Lift: 4.0
--------------------------------------------------
Rule 72: frozenset({'low fat yogurt'}) -> frozenset({'green tea', 'honey'})
Support: 0.25, Confidence: 1.0, Lift: 4.0
--------------------------------------------------
Rule 73: frozenset({'green tea', 'honey', 'low fat yogurt'}) -> frozenset({'tomato juice'})
Support: 0.25, Confidence: 1.0, Lift: 4.0
--------------------------------------------------
Rule 74: frozenset({'green tea', 'tomato juice', 'low fat yogurt'}) -> frozenset({'honey'})
Support: 0.25, Confidence: 1.0, Lift: 4.0
--------------------------------------------------
Rule 75: frozenset({'green tea', 'tomato juice', 'honey'}) -> frozenset({'low fat yogurt'})
Support: 0.25, Confidence: 1.0, Lift: 4.0
--------------------------------------------------
Rule 76: frozenset({'honey', 'tomato juice', 'low fat yogurt'}) -> frozenset({'green tea'})
Support: 0.25, Confidence: 1.0, Lift: 4.0
--------------------------------------------------
Rule 77: frozenset({'green tea', 'low fat yogurt'}) -> frozenset({'tomato juice', 'honey'})
Support: 0.25, Confidence: 1.0, Lift: 4.0
--------------------------------------------------
Rule 78: frozenset({'green tea', 'honey'}) -> frozenset({'tomato juice', 'low fat yogurt'})
Support: 0.25, Confidence: 1.0, Lift: 4.0
--------------------------------------------------
Rule 79: frozenset({'green tea', 'tomato juice'}) -> frozenset({'honey', 'low fat yogurt'})
Support: 0.25, Confidence: 1.0, Lift: 4.0
--------------------------------------------------
Rule 80: frozenset({'honey', 'low fat yogurt'}) -> frozenset({'green tea', 'tomato juice'})
Support: 0.25, Confidence: 1.0, Lift: 4.0
--------------------------------------------------
Rule 81: frozenset({'tomato juice', 'low fat yogurt'}) -> frozenset({'green tea', 'honey'})
Support: 0.25, Confidence: 1.0, Lift: 4.0
--------------------------------------------------
Rule 82: frozenset({'tomato juice', 'honey'}) -> frozenset({'green tea', 'low fat yogurt'})
Support: 0.25, Confidence: 1.0, Lift: 4.0
--------------------------------------------------
Rule 83: frozenset({'green tea'}) -> frozenset({'honey', 'tomato juice', 'low fat yogurt'})
Support: 0.25, Confidence: 1.0, Lift: 4.0
--------------------------------------------------
Rule 84: frozenset({'low fat yogurt'}) -> frozenset({'green tea', 'tomato juice', 'honey'})
Support: 0.25, Confidence: 1.0, Lift: 4.0
--------------------------------------------------
Rule 85: frozenset({'honey'}) -> frozenset({'green tea', 'tomato juice', 'low fat yogurt'})
Support: 0.25, Confidence: 1.0, Lift: 4.0
--------------------------------------------------
Rule 86: frozenset({'tomato juice'}) -> frozenset({'green tea', 'honey', 'low fat yogurt'})
Support: 0.25, Confidence: 1.0, Lift: 4.0
--------------------------------------------------

# Interview Questions:

1.Lift is a metric used to evaluate the strength of an association rule. It measures how much more likely the consequent (right-hand side) of a rule is to occur when the antecedent (left-hand side) occurs, compared to when the antecedent and consequent are independent of each other.

#Lift helps to understand whether the rule is actually meaningful or if the antecedent and consequent occur together by chance.
#A higher lift value indicates a stronger association, which makes the rule more interesting and actionable for business decisions.


2.Support measures the frequency or proportion of transactions that contain both the antecedent and consequent of a rule.
#Confidence(A→B)=Support(A)/Support(A∩B)
​

#3. Computational Complexity:
Apriori algorithm, the most common algorithm for association rule mining, can be computationally expensive, especially for large datasets. This is because it needs to scan the entire dataset multiple times to count itemsets, which makes it slow for large numbers of transactions and items

#Association rules generally focus on binary relationships (e.g., “If A, then B”). More complex relationships, such as those involving multiple items or those requiring more sophisticated machine learning models, are not well-captured by traditional association rule mining.